import type { Business } from "@echelon/types";

export const businesses: Business[] = [
  {
    id: "clxhair",
    name: "Luma Hair Studio",
    slug: "luma-hair-studio",
    category: "Hair Salon",
    logoUrl: "/logos/luma.svg",
    coverUrl: "/covers/luma.jpg",
    rating: 4.9,
    reviewCount: 428,
    suburb: "Northbridge",
    city: "Perth",
    tags: ["Colour", "Cuts", "Bridal"],
    services: [
      {
        id: "svc-cut",
        businessId: "clxhair",
        name: "Signature Cut & Finish",
        priceCents: 8900,
        durationMinutes: 60,
        description: "Consultation, wash, precision cut and blow-dry finish.",
        availability: ["09:00", "11:30", "14:00", "16:30"],
      },
      {
        id: "svc-colour",
        businessId: "clxhair",
        name: "Gloss Colour Refresh",
        priceCents: 14500,
        durationMinutes: 90,
        description: "Tone, gloss and blow dry for luminous colour maintenance.",
        availability: ["10:00", "13:30", "15:30"],
      },
      {
        id: "svc-bridal",
        businessId: "clxhair",
        name: "Bridal Hair & Trial",
        priceCents: 28000,
        durationMinutes: 150,
        description: "Full bridal styling plus one trial session.",
        availability: ["09:00", "13:00"],
      },
    ],
  },
  {
    id: "clxphoto",
    name: "North Star Weddings",
    slug: "north-star-weddings",
    category: "Photography",
    logoUrl: "/logos/northstar.svg",
    coverUrl: "/covers/wedding.jpg",
    rating: 4.95,
    reviewCount: 196,
    suburb: "Fremantle",
    city: "Perth",
    tags: ["Weddings", "Events", "Portraits"],
    services: [
      {
        id: "svc-discovery",
        businessId: "clxphoto",
        name: "Wedding Discovery Call",
        priceCents: 0,
        durationMinutes: 30,
        description: "Plan coverage, style and package options with your photographer.",
        availability: ["10:00", "13:00", "17:00"],
      },
      {
        id: "svc-fullday",
        businessId: "clxphoto",
        name: "Full Day Wedding Coverage",
        priceCents: 380000,
        durationMinutes: 600,
        description: "10 hours of coverage, two photographers, 600+ edited images.",
        availability: ["08:00", "09:00"],
      },
    ],
  },
  {
    id: "clxmassage",
    name: "Zenith Wellness",
    slug: "zenith-wellness",
    category: "Massage",
    logoUrl: "/logos/zenith.svg",
    coverUrl: "/covers/massage.jpg",
    rating: 4.8,
    reviewCount: 312,
    suburb: "Subiaco",
    city: "Perth",
    tags: ["Remedial", "Relaxation", "Sports"],
    services: [
      {
        id: "svc-remedial-60",
        businessId: "clxmassage",
        name: "Remedial Massage 60 min",
        priceCents: 9500,
        durationMinutes: 60,
        description: "Targeted deep-tissue therapy for pain relief and recovery.",
        availability: ["09:00", "10:30", "13:00", "15:00", "16:30"],
      },
      {
        id: "svc-relax-90",
        businessId: "clxmassage",
        name: "Relaxation Massage 90 min",
        priceCents: 13500,
        durationMinutes: 90,
        description: "Full body Swedish massage to release tension and restore calm.",
        availability: ["09:30", "11:30", "14:00"],
      },
      {
        id: "svc-sports",
        businessId: "clxmassage",
        name: "Sports Recovery",
        priceCents: 11000,
        durationMinutes: 75,
        description: "Pre or post-event treatment for athletes and active clients.",
        availability: ["07:00", "12:00", "17:00"],
      },
    ],
  },
  {
    id: "clxdj",
    name: "BassLine Events",
    slug: "bassline-events",
    category: "DJ & Entertainment",
    logoUrl: "/logos/bassline.svg",
    coverUrl: "/covers/dj.jpg",
    rating: 4.85,
    reviewCount: 89,
    suburb: "Leederville",
    city: "Perth",
    tags: ["Weddings", "Corporates", "Birthdays"],
    services: [
      {
        id: "svc-dj-wedding",
        businessId: "clxdj",
        name: "Wedding DJ Package",
        priceCents: 220000,
        durationMinutes: 480,
        description: "8 hours coverage, MC services, lighting rig, wireless microphone.",
        availability: ["17:00", "18:00"],
      },
      {
        id: "svc-dj-party",
        businessId: "clxdj",
        name: "Party & Birthday DJ",
        priceCents: 95000,
        durationMinutes: 240,
        description: "4 hours, full sound system, custom playlist consultation.",
        availability: ["18:00", "20:00", "21:00"],
      },
      {
        id: "svc-dj-consult",
        businessId: "clxdj",
        name: "DJ Consultation",
        priceCents: 0,
        durationMinutes: 30,
        description: "Discuss your event, music style and package options.",
        availability: ["10:00", "13:00", "15:00"],
      },
    ],
  },
  {
    id: "clxbeauty",
    name: "Soleil Beauty Lounge",
    slug: "soleil-beauty-lounge",
    category: "Beauty",
    logoUrl: "/logos/soleil.svg",
    coverUrl: "/covers/beauty.jpg",
    rating: 4.75,
    reviewCount: 541,
    suburb: "Mount Lawley",
    city: "Perth",
    tags: ["Nails", "Facials", "Brows"],
    services: [
      {
        id: "svc-facial",
        businessId: "clxbeauty",
        name: "Signature Glow Facial",
        priceCents: 12500,
        durationMinutes: 75,
        description: "Customised for your skin type — cleanse, exfoliate, mask, hydrate.",
        availability: ["09:00", "11:00", "14:00", "16:00"],
      },
      {
        id: "svc-nails",
        businessId: "clxbeauty",
        name: "Gel Manicure & Pedicure",
        priceCents: 9500,
        durationMinutes: 90,
        description: "Long-lasting gel colour on hands and feet with cuticle care.",
        availability: ["10:00", "12:00", "14:30", "16:30"],
      },
      {
        id: "svc-brows",
        businessId: "clxbeauty",
        name: "Brow Lamination & Tint",
        priceCents: 7500,
        durationMinutes: 60,
        description: "Lifting, setting and tinting for defined, brushed-up brows.",
        availability: ["09:30", "11:30", "15:00"],
      },
    ],
  },
  {
    id: "clxfitness",
    name: "Apex Performance",
    slug: "apex-performance",
    category: "Personal Training",
    logoUrl: "/logos/apex.svg",
    coverUrl: "/covers/fitness.jpg",
    rating: 4.92,
    reviewCount: 167,
    suburb: "West Perth",
    city: "Perth",
    tags: ["Strength", "HIIT", "Nutrition"],
    services: [
      {
        id: "svc-pt-session",
        businessId: "clxfitness",
        name: "1-on-1 Personal Training",
        priceCents: 11000,
        durationMinutes: 60,
        description: "Tailored training session with a certified coach.",
        availability: ["06:00", "07:00", "08:00", "17:00", "18:00", "19:00"],
      },
      {
        id: "svc-pt-pack10",
        businessId: "clxfitness",
        name: "10-Session Training Pack",
        priceCents: 95000,
        durationMinutes: 60,
        description: "Commit to results — 10 sessions, progress tracking and program design.",
        availability: ["06:00", "07:00", "08:00", "17:00", "18:00"],
      },
      {
        id: "svc-consult",
        businessId: "clxfitness",
        name: "Fitness Assessment",
        priceCents: 5000,
        durationMinutes: 45,
        description: "Body composition, movement screen and goal-setting session.",
        availability: ["09:00", "12:00", "15:00"],
      },
    ],
  },
];
